### ISSUE TITLE
Calling `bottle :unneeded` is deprecated

### ISSUE THREAD

**Issue by mkushakov** [tilt-dev/homebrew-tap#3]
In MacOS 12 after executing `brew update` there is a depreciation warning.
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the tilt-dev/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/tilt-dev/homebrew-tap/tilt.rb:9
```

**Comment by nicks** [comment]
thanks for the report!

ya, this caught everyone by surprise, and it's taking time for it to trickle through all the release tooling https://github.com/goreleaser/goreleaser/pull/2591
